extends: ['@commitlint/config-conventional']
rules:
  subject-case: [0, never, 'sentence-case']
  subject-full-stop: [2, 'always', '.']
  type-enum: 
    - 2
    - always
    - ['build', 'chore', 'ci', 'docs', 'feature', 'fix', 'revert', 'wip']
