
version: 1
formatters:
  human:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  json:
    (): app.logger.JSONFormatter
    fmt_keys: 
      # foo : bar
      - levelname
      - message
      - timestamp
      - name
      - module
      - funcName
      - lineno
      - threadName
handlers:
  stdout_dev:
    class: rich.logging.RichHandler
    level: DEBUG
  # stdout:
  #   formatter: human
  #   stream: ext://sys.stdout
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: human
    stream: ext://sys.stderr
  file_json:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/captura.jsonl
    maxBytes: 10000000
    backupCount: 5
  # queue_handler:
  #   class: logging.handlers.QueueHandler
  #   # handlers:
  #   # - stdout
  #   # - file_json
  #   respect_handler_level: true
loggers:
  root:
    level: DEBUG
    handlers:
      - stdout_dev
      - file_json
  app.views.base:
    level: WARNING
  app.depends:
    level: DEBUG

