
version: 1
formatters:
  # human:
  #   format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
  json:
    (): captura.logger.JSONFormatter
    fmt_keys: 
      # foo : bar
      - levelname
      - timestamp
      - name
      - module
      - funcName
      - lineno
      - threadName
handlers:
  stdout_dev:
    class: rich.logging.RichHandler
    level: DEBUG
  stdout_min:
    class: logging.StreamHandler
    # formatter: human 
    # ^^^^^^^^^^^^^^^^
    # NOTE: Breaks logging
    stream: ext://sys.stdout
  stderr:
    class: logging.StreamHandler
    # level: WARNING
    # formatter: human
    stream: ext://sys.stderr
  # file_json:
  #   class: logging.handlers.RotatingFileHandler
  #   level: DEBUG
  #   formatter: json
  #   filename: logs/captura.jsonl
  #   maxBytes: 10000000
  #   backupCount: 5
# disable_existing_loggers: True
loggers:
  root:
    level: INFO
    handlers:
      - stdout_dev
      # - file_json
  captura.controllers.delete:
    level: DEBUG
