---
name: captura-ci
services:
  server:
    # NOTE: Should build before running for caching.
    build:
      context: '..'
      target: ci
    extends:
      file: ./compose.base.yaml
      service: server
    # NOTE: Adding an image tag that is version specific should not be done
    #       as this must be consistent with the caching config - updating the
    #       version string in the caching config requires the ``workflow`` 
    #       permission for the pipeline, which is overkill imo.
    image: acederberg/captura-ci:latest
    networks:
      captura: {}
  db:
    extends:
      file: ./compose.base.yaml
      service: db
    networks:
      captura: {}
networks:
  captura:
    driver: bridge

