---
# version: '3.9'
name: captura
services:
  server:
    build:
      context: '..'
      dockerfile: './docker/dockerfile'
      target: development
    image: acederberg/captura-development:0.1.5
    container_name: captura-server
    ports: 
      - target: 8080
        published: 8080
    networks:
      captura: {}
    tty: true
    volumes:
      - '.venv:/home/captura/.venv'
      - '..:/home/captura/app'
      # NOTE: Overwrite the data volumes since they slow down refresh.
      - /home/captura/app/docker/.data
      - /home/captura/app/docker/.venv
  db:
    image: mysql:8
    container_name: captura-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: captura
      MYSQL_USER: captura
      MYSQL_PASSWORD: changeme
    networks:
      captura: {}
    volumes:
      - .data/mysql:/var/lib/mysql
networks:
  captura:
    driver: bridge


