---
# version: '3.9'
services:
  server:
    build:
      context: '.'
      dockerfile: './dockerfile'
      target: development
    image: acederberg/captura/development:0.1.1
    container_name: captura-server
    ports: 
      - target: 8080
        published: 8080
    networks:
      captura: {}
    tty: true
    volumes:
      - 'venv:/home/adrian/.venv'
      - '..:/home/captura/app'
  db:
    image: mysql:8
    container_name: captura-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: captura
      MYSQL_USER: captura
      MYSQL_PASSWORD: changeme
    networks:
      captura: {}
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  venv: null
  mysql-data: null
networks:
  captura:
    driver: bridge


