---
# version: '3.9'
services:
  server:
    build:
      context: '.'
      dockerfile: './dockerfile'
      target: dev
    container_name: captura-server
    ports: 
      - target: 8080
        published: 8080
    networks:
      captura: {}
    tty: true
    volumes:
      - '..:/home/captura/app'
  db:
    image: mysql:8
    container_name: captura-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: captura
      MYSQL_USER: captura
      MYSQL_PASSWORD: changeme
    networks:
      captura: {}
networks:
  captura:
    driver: bridge


