version: 1
formatters:
  json:
    (): app.logger.JSONFormatter
    fmt_keys: 
      - levelname
      - timestamp
      - name
      - module
      - funcName
      - lineno
      - threadName

handlers:
  # file_json:
  #   class: logging.handlers.RotatingFileHandler
  #   level: DEBUG
  #   formatter: json
  #   filename: /home/captura/logs/captura.jsonl
  #   maxBytes: 10000000
  #   backupCount: 5
  json_socket:
    class: logging.handlers.SocketHandler
    host: "0.0.0.0"
    port: 8081
    formatter: json
    level: INFO
  json_human:
    class: rich.logging.RichHandler
    formatter: json
    level: INFO
  stdout_dev:
    class: rich.logging.RichHandler
    level: DEBUG
    
loggers:
  root:
    level: DEBUG
    handlers:
      # - json_socket
      - json_human
      # - stdout_dev

